version: '2.1'
services:
    redisdb:
        image: redis
        volumes:
            - ~/orgidBot/redisData:/data
        ports:
            - 6379:6379
        networks:
            - localdev
networks:
    localdev:
        driver: bridge
